"use client";
import {useMemo,useRef,useState} from "react";
type Scene={id:number;text:string;prompt:string;video?:string};
const lock="STRICT CHARACTER LOCK: Use uploaded character sheets as canonical designs. Preserve exact faces, hair, skin tones, proportions, costumes, colors, accessories and weapons. Never redesign or substitute. Maintain continuity with every previous clip.";
export default function Home(){
 const[step,setStep]=useState(0),[chars,setChars]=useState<{name:string,url:string}[]>([]),[title,setTitle]=useState(""),[story,setStory]=useState(""),[style,setStyle]=useState("Cinematic anime"),[scenes,setScenes]=useState<Scene[]>([]),[copied,setCopied]=useState(0),[playing,setPlaying]=useState(false),[pi,setPi]=useState(0);const player=useRef<HTMLVideoElement>(null);const ready=useMemo(()=>scenes.filter(s=>s.video),[scenes]);
 const addChars=(f:FileList|null)=>f&&setChars(x=>[...x,...Array.from(f).map(v=>({name:v.name,url:URL.createObjectURL(v)}))]);
 const build=()=>{let p=story.split(/(?<=[.!?])\s+|\n+/).map(x=>x.trim()).filter(Boolean);if(p.length<2){let w=story.split(/\s+/);p=Array.from({length:Math.ceil(w.length/28)},(_,i)=>w.slice(i*28,i*28+28).join(" "))}setScenes(p.slice(0,225).map((text,i)=>({id:Date.now()+i,text,prompt:`${lock}\n\nCLIP ${i+1} — exactly 8 seconds. ${style} movie. ${text}\n\nCinematic composition, expressive natural motion, detailed environment, smooth camera movement, no captions, no watermark, 16:9.`})));setStep(3)};
 const copy=async(s:Scene)=>{await navigator.clipboard.writeText(s.prompt);setCopied(s.id);setTimeout(()=>setCopied(0),1300)};
 const upload=(id:number,f:FileList|null)=>{if(f?.[0])setScenes(x=>x.map(s=>s.id===id?{...s,video:URL.createObjectURL(f[0])}:s))};
 const play=()=>{if(ready.length){setPi(0);setPlaying(true);setTimeout(()=>player.current?.play(),80)}};const next=()=>{if(pi<ready.length-1){setPi(x=>x+1);setTimeout(()=>player.current?.play(),80)}else setPlaying(false)};
 return <main><header><button aria-label="Peanut home" onClick={()=>setStep(0)}>🐶 <b>Peanut</b><small>AI MOVIE MAKER</small></button><span>✦ Daily Free-Credit Workflow</span></header>
 {step===0&&<section className="hero"><p className="gold">FROM STORY TO REAL VIDEO CLIPS</p><h1>Your movie studio.<br/><em>Without the confusion.</em></h1><p>Peanut prepares every 8-second prompt. Generate clips with daily free credits, upload them, and play your movie in order.</p><button className="primary big" onClick={()=>setStep(1)}>Start My Movie →</button><div className="flow">{[["01","Upload sheets"],["02","Paste story"],["03","Generate free"],["04","Upload MP4s"]].map(x=><article key={x[0]}><i>{x[0]}</i><b>{x[1]}</b></article>)}</div></section>}
 {step===1&&<section className="page"><Nav n={1}/><p className="gold">CHARACTER VAULT</p><h2>Upload character sheets</h2><p className="sub">No character forms. Identity lock is automatic.</p><label className="drop"><input type="file" accept="image/*" multiple onChange={e=>addChars(e.target.files)}/><strong>＋</strong><b>Choose character sheets</b><small>PNG, JPG or WEBP</small></label><div className="chars">{chars.map((c,i)=><article key={c.url}><img src={c.url} alt="Character sheet"/><button onClick={()=>setChars(chars.filter((_,j)=>j!==i))}>×</button><small>{c.name}</small></article>)}</div><aside>🔒 Exact character continuity is added to every prompt.</aside><div className="actions"><button onClick={()=>setStep(0)}>Back</button><button className="primary" disabled={!chars.length} onClick={()=>setStep(2)}>Continue →</button></div></section>}
 {step===2&&<section className="page"><Nav n={2}/><p className="gold">STORY ENGINE</p><h2>Tell Peanut the whole story</h2><p className="sub">It becomes ready-to-copy 8-second video prompts.</p><label>Movie title<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="The Six Lights of Lumeria"/></label><label>Full story<textarea value={story} onChange={e=>setStory(e.target.value)} placeholder="Paste your complete story…"/></label><label>Movie style<select value={style} onChange={e=>setStyle(e.target.value)}><option>Cinematic anime</option><option>Realistic cinematic</option><option>3D animated film</option><option>Illustrated fantasy</option></select></label><div className="actions"><button onClick={()=>setStep(1)}>Back</button><button className="primary" disabled={story.length<20} onClick={build}>✦ Build My Movie Plan</button></div></section>}
 {step===3&&<section className="board"><Nav n={3}/><div className="boardHead"><div><p className="gold">PRODUCTION BOARD</p><h2>{title||"Untitled Movie"}</h2><p className="sub">{scenes.length} clips • 8 seconds each</p></div><div className="meter"><b>{scenes.length?Math.round(ready.length/scenes.length*100):0}%</b><span><i style={{width:`${scenes.length?ready.length/scenes.length*100:0}%`}}/></span><small>{ready.length} of {scenes.length} clips uploaded</small></div></div><aside className="routine"><b>Daily routine:</b> ① Copy prompt　② Generate in Dreamina　③ Download MP4　④ Upload here</aside><div className="toolbar"><a href="https://dreamina.capcut.com/ai-tool/video-generator" target="_blank">Open Dreamina ↗</a><button onClick={()=>setStep(2)}>Edit story</button><button className="primary" disabled={!ready.length} onClick={play}>▶ Play Movie</button></div><div className="scenes">{scenes.map((s,i)=><article className={s.video?"done":""} key={s.id}><div className="num"><small>CLIP</small><b>{String(i+1).padStart(3,"0")}</b><small>8 SEC</small></div><div className="sceneText"><p>{s.text}</p><details><summary>View full AI prompt</summary><pre>{s.prompt}</pre></details><div><button className="copy" onClick={()=>copy(s)}>{copied===s.id?"✓ Copied":"⧉ Copy Prompt"}</button><a href="https://dreamina.capcut.com/ai-tool/video-generator" target="_blank">Generate ↗</a><label className={s.video?"uploaded":""}>{s.video?"✓ MP4 Added":"＋ Upload MP4"}<input type="file" accept="video/*" onChange={e=>upload(s.id,e.target.files)}/></label></div></div>{s.video&&<video src={s.video} controls playsInline/>}</article>)}</div></section>}
 {playing&&<div className="cinema"><button onClick={()=>setPlaying(false)}>×</button><video ref={player} key={ready[pi]?.video} src={ready[pi]?.video} autoPlay controls playsInline onEnded={next}/><h3>{title||"My Movie"}</h3><p>Clip {pi+1} of {ready.length}</p></div>}</main>}
function Nav({n}:{n:number}){return <nav><span className={n>=1?"on":""}>1 Character sheets</span><i/><span className={n>=2?"on":""}>2 Story</span><i/><span className={n>=3?"on":""}>3 Production</span></nav>}
